branches:
  only:
    - master

language: cpp
dist: xenial

cache: ccache

jobs:
  include:
      # Check clang format and flake8 in the first stage
    - stage: "Code formatting"
      name: "Clang-format"
      before_install: sh .travis/before_install.sh
      script: sh .travis/check_clang_format.sh
    - name: "Flake8"
      before_install: sh .travis/before_install.sh
      script: sh .travis/check_flake8.sh
      # Then start parallel build of gcc and clang in the Test stage
    - stage: "Unit tests"
      # works on Precise and Trusty
      - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
  #          - clang-5.0
      env:
        - JOBS_EVAL="CC=gcc-7 && CXX=g++-7"
#        - JOBS_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      before_install:
        - eval "${JOBS_EVAL}"
      install: sh .travis/install.sh
      script: sh .travis/run_tests.sh
