if: type = pull_request

language: cpp
compiler:
  - gcc
  - clang
dist: xenial

jobs:
  include:
    - stage: build
      before_install: sh .travis/before_install.sh
      install: sh .travis/install.sh
      script:
        - mkdir -p build
        - mkdir -p install
        - cd build
        - cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX=../install ..
        - make -j2 install
    - stage: test
      script:
        - ./units/test/scipp_units_test
        - ./core/test/scipp_core_test
        - python3 -m pip install -r ../scippy/requirements.txt
        - export PYTHONPATH=$PYTHONPATH:../install
        - cd ../scippy
        - python3 -m unittest discover test
